#!/bin/bash

set -e

if ! [ -x "env/bin/octodns-sync" ]; then
  script/bootstrap
fi

source env/bin/activate

. script/provider-credentials

env/bin/octodns-sync \
    --config=./config/production.yaml \
    "$@"
