#!/bin/bash

set -e

. script/provider-credentials

for zone in ${ZONES}; do
    echo "Processing zone $zone."
    octodns dump \
      --config-file "$(pwd)/config/production.yaml" \
      --output-dir "$(pwd)/config" \
      "$zone." cloudflare \
      "$@"
done
