#!/bin/sh

ZONES=""
ZONES="${ZONES} jekyllrb.com"

export DOCKER_IMAGE="parkr/octodns:e23579686537136b1c2fdd7f52dba430e278712b"
export CLOUDFLARE_TOKEN="$(cat ~/.config/cloudflare/parker-token)"
export CLOUDFLARE_EMAIL="$(cat ~/.config/cloudflare/parker-email)"

octodns() {
  local subcommand="$1"
  shift
  if [ -z "$subcommand" ]; then
    echo "no octodns subcommand specified."
    exit 1
  fi
  cwd="$(pwd)"

  docker run -it --rm \
    -v "$cwd":"$cwd" \
    -w "$cwd" \
    -e CLOUDFLARE_EMAIL="$CLOUDFLARE_EMAIL" \
    -e CLOUDFLARE_TOKEN="$CLOUDFLARE_TOKEN" \
    "$DOCKER_IMAGE" \
    octodns-"$subcommand" "$@"
}
