#!/bin/sh

ZONES=""
ZONES="${ZONES} jekyllrb.com"

# This integrates https://github.com/github/octodns/pull/402.
export DOCKER_IMAGE="parkr/octodns:e23579686537136b1c2fdd7f52dba430e278712b"
export CLOUDFLARE_TOKEN="$(cat ~/.config/cloudflare/jekyll-dns-api-token)"

octodns() {
  local subcommand="$1"
  shift
  if [ -z "$subcommand" ]; then
    echo "no octodns subcommand specified."
    exit 1
  fi
  cwd="$(pwd)"

  docker run -it --rm \
    -v "$cwd":"$cwd" \
    -w "$cwd" \
    -e CLOUDFLARE_TOKEN="$CLOUDFLARE_TOKEN" \
    "$DOCKER_IMAGE" \
    octodns-"$subcommand" "$@"
}
