#!/bin/bash

ZONES=""
ZONES="${ZONES} jekyllrb.com"

# This integrates https://github.com/github/octodns/pull/402.
export DOCKER_IMAGE="parkr/octodns:cf3dc943152ea6ed005969ec835513ca150a3de0"
export CLOUDFLARE_TOKEN="$(cat ~/.config/cloudflare/jekyll-dns-api-token)"

octodns() {
  local subcommand="$1"
  shift
  if [ -z "$subcommand" ]; then
    echo "no octodns subcommand specified."
    exit 1
  fi
  cwd="$(pwd)"

  docker run -it --rm \
    -v "$cwd":"$cwd" \
    -w "$cwd" \
    -e CLOUDFLARE_TOKEN="$CLOUDFLARE_TOKEN" \
    "$DOCKER_IMAGE" \
    octodns-"$subcommand" "$@"
}

octodns_debug() {
  cwd="$(pwd)"
  docker run -it --rm \
    -v "$cwd":"$cwd" \
    -w "$cwd" \
    -e CLOUDFLARE_TOKEN="$CLOUDFLARE_TOKEN" \
    "$DOCKER_IMAGE" \
    /bin/bash -l
}
